### PR TITLE
Replaces Write-Host with Write-Verbose

### PR DESCRIPTION
**Pull request by ahmedig**
Write-Host is harmful, and also not supported in VSTS automation tasks.

### CODE REVIEW

**Comment by timabell** [comment]
Are you okay with this being under the newly added MIT license? Also just for my info do you have a reference as to why it's bad so I can learn more? Thanks

**Comment by ahmedig** [comment]
Hey Tim,

Write-Host doesn't work in VSTS build pipeline as you know. It was breaking for me until I replaced it with Write-Verbose.
Also have a look at this please:
http://www.jsnover.com/blog/2013/12/07/write-host-considered-harmful/

Thanks

**Comment by timabell** [comment]
Cheers, and are you okay with the new license?

**Comment by ahmedig** [comment]
Can you please be more clear? What's special about the license?

Sent from my iPhone

On 8 Mar 2017, at 8:23 am, Tim Abell <notifications@github.com> wrote:

Cheers, and are you okay with the new license?

**Comment by timabell** [comment]
Sure. The licence has only just been added to the project, so I want to make sure you are okay with this change before including your PR in the project.

**Comment by ahmedig** [comment]
Yeah sure am ok

Sent from my iPhone

On 8 Mar 2017, at 8:23 am, Tim Abell <notifications@github.com> wrote:

Cheers, and are you okay with the new license?

**Pull request merged**
